Password Strength
MyCryptoHQ/quill pull request #190
Opened 2022-01-25 13:34 UTC by FrederikBolding

2022-01-26 13:19 UTC, FrederikBolding commented
[sc-9447]

2022-01-27 11:29 UTC, Mrtenz requested changes

2022-01-27 11:29 UTC, Mrtenz commented on packages/quill/src/app/components/FormPasswordStrength.tsx
> +  const result = zxcvbn((value as unknown) as string);
Maybe memoize this

2022-01-27 11:29 UTC, Mrtenz commented on packages/quill/src/app/screens/CreatePassword.tsx
> +          <Box width="100%" mt="2" color="BLUE_GREY"></Box>
What's this for?

2022-01-27 11:33 UTC, FrederikBolding commented on packages/quill/src/app/screens/CreatePassword.tsx
> +          <Box width="100%" mt="2" color="BLUE_GREY"></Box>
Remnant of old code - removing

2022-01-27 11:33 UTC, FrederikBolding commented on packages/quill/src/app/components/FormPasswordStrength.tsx
> +  const result = zxcvbn((value as unknown) as string);
Good idea

2022-01-27 12:22 UTC, Mrtenz approved these changes

2022-01-27 12:23 UTC, merged