View Signed TX
MyCryptoHQ/quill pull request #202
Opened 2022-02-10 08:15 UTC by FrederikBolding

2022-02-10 08:15 UTC, FrederikBolding commented
[sc-9513]

2022-02-14 13:55 UTC, Mrtenz requested changes

2022-02-14 13:55 UTC, Mrtenz commented on packages/quill/src/app/screens/Transaction.tsx
> +          ) : (
Do we only want to show the button after 5 minutes? My understanding was that we'd show both the button and the message, but hide the message after 5 minutes.

2022-02-14 16:56 UTC, Mrtenz approved these changes

2022-02-16 08:31 UTC, merged